apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bells-and-whistles
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bell
            image: gcr.io/the-gathering-195011/github-gathering-bells_and_whistles:latest
          restartPolicy: OnFailure
